sudo: required
services:
  - docker

before_install:
  - docker build -t tlsingh1/docker-react -f Dockerfile.dev .

script:
  - docker run tlsingh1/docker-react npm run test -- --coverage

deploy:
  provider: elsticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elsticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_ACCESS_KEY"
